#!/usr/bin/env bash
# 02_inventory.sh — generate hosts.ini from the running minecraft EC2 instance.

set -euo pipefail
# shellcheck source=_env.sh
source "$(dirname "$0")/_env.sh"

HOSTS_FILE="hosts.ini"

echo "==> Verifying AWS credentials"
aws sts get-caller-identity >/dev/null || {
  echo "ERROR: AWS credentials missing or expired. Refresh from Learner Lab." >&2
  exit 1
}

echo "==> Looking up running minecraft instance for project '$PROJECT_TAG'"
PUBLIC_IP=$(aws ec2 describe-instances \
  --filters "Name=tag:Project,Values=$PROJECT_TAG" \
            "Name=tag:Role,Values=minecraft" \
            "Name=instance-state-name,Values=running" \
  --query 'Reservations[0].Instances[0].PublicIpAddress' \
  --output text 2>/dev/null || echo "None")

if [[ "$PUBLIC_IP" == "None" || -z "$PUBLIC_IP" ]]; then
  echo "ERROR: no running minecraft instance found for $PROJECT_TAG. Did 01_provision.sh succeed?" >&2
  exit 1
fi

echo "    public IPv4: $PUBLIC_IP"

echo "==> Writing $HOSTS_FILE"
cat > "$HOSTS_FILE" <<EOF
# Ansible inventory for ansible-minecraft-aws.
# Generated by 02_inventory.sh. DO NOT EDIT BY HAND — regenerated on each run.

[minecraft]
mc1 ansible_host=${PUBLIC_IP}

[minecraft:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=${KEY_FILE}
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=accept-new'
EOF

echo
echo "==> Inventory complete."
echo "    cat $HOSTS_FILE  to inspect"
echo "    next: ./03_configure.sh"
