#!/usr/bin/env bash
# 02_inventory.sh — generate hosts.ini from the running minecraft EC2 instance.

set -euo pipefail
# shellcheck source=_env.sh
source "$(dirname "$0")/_env.sh"

HOSTS_FILE="hosts.ini"

echo "==> Verifying AWS credentials"
aws sts get-caller-identity >/dev/null || {
  echo "ERROR: AWS credentials missing or expired. Refresh from Learner Lab." >&2
  exit 1
}

echo "==> Looking up Elastic IP for project '$PROJECT_TAG'"
EIP=$(aws ec2 describe-addresses \
  --filters "Name=tag:Project,Values=$PROJECT_TAG" \
  --query 'Addresses[0].PublicIp' \
  --output text 2>/dev/null || echo "None")

if [[ "$EIP" == "None" || -z "$EIP" ]]; then
  echo "ERROR: no Elastic IP found for $PROJECT_TAG. Did 01_provision.sh succeed?" >&2
  exit 1
fi

echo "    EIP: $EIP"

# Preserve a copy of any pre-existing hosts.ini the first time we overwrite it.
if [[ -f "$HOSTS_FILE" && ! -f "${HOSTS_FILE}.template" ]]; then
  cp "$HOSTS_FILE" "${HOSTS_FILE}.template"
  echo "    backed up existing hosts.ini -> ${HOSTS_FILE}.template"
fi

echo "==> Writing $HOSTS_FILE"
cat > "$HOSTS_FILE" <<EOF
# Ansible inventory for ansible-minecraft-aws.
# Generated by 02_inventory.sh. DO NOT EDIT BY HAND — regenerated on each run.

[minecraft]
mc1 ansible_host=${EIP}

[minecraft:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=${KEY_FILE}
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=accept-new'
EOF

echo
echo "==> Inventory complete."
echo "    cat $HOSTS_FILE  to inspect"
echo "    next: ./03_configure.sh"
